### ISSUE TITLE
CCEmuX api does not appear when running Phoenix inside of CCEmuX

### ISSUE THREAD

**Issue by EmmaKnijn** [Phoenix-ComputerCraft/issues#7]
CraftOS
![image](https://user-images.githubusercontent.com/64010592/187975341-9526eae4-de75-40b9-bd91-9ae93e7e0f79.png)

Phoenix
![image](https://user-images.githubusercontent.com/64010592/187975636-db6f61e3-6cd1-4c5f-bfed-ef7685a1ab71.png)

**Comment by Ocawesome101** [comment]
phoenix APIs != CraftOS APIs.  presumably it's present as a device, or you have to `local ccemux = require("ccemux")`, or it's just not implemented.

**Comment by MCJack123** [comment]
`ccemux` is intentionally left out of the global environment. I've added two new syscalls, `attach` and `detach`, to allow manipulating peripherals (including computers) on both CraftOS-PC and CCEmuX. `os.time("nano")` also now supports `ccemux.nanoTime()`, as does the process timer. I will not be implementing the rest of the API because the rest is a bit too niche or unsafe to warrant extra syscalls - if you'd like to expose them, feel free to make your own kernel module (using the new [kernel API docs](https://phoenix.madefor.cc/kernel-api.html)!).
